### ISSUE TITLE
Distributed file should not be ES6

### ISSUE THREAD

**Issue by 03xb7** [kevva/strict-uri-encode#6]
`index.js` is distributed as is (meaning with ES6 code) through npm. It prevents using your lib without a transpiler such as Babel.

Cheers

**Comment by SamVerschueren** [comment]
Use `1.1.0` if you want to use it in the browser.

**Comment by jnields** [comment]
There is nothing breaking about just using a function instead of an arrow function

**Comment by 03xb7** [comment]
It does if you're in the browser and have to support some old browsers such as IE11. In my case, I had to integrate `strict-uri-encode` to the babel flow, meaning modifying my build, meaning it is a breaking change.

**Comment by WillBeebe** [comment]
I had the same issue. If you're using a transpiler like babel, it can't reassign exports with how you have it set up, if you change the syntax a little it would be able to. Since I couldn't get around it though I had to use a function in my repo and drop the dependency on this.
