### ISSUE TITLE
Troubles with UglifyJS

### ISSUE THREAD

**Issue by kud** [kevva/strict-uri-encode#7]
I just added your lib to my app as I need it. And after some checks, I just saw that Uglify does not like this line in my app:

```
/***/ (function(module, exports, __webpack_require__) {

"use strict";

module.exports = str => encodeURIComponent(str).replace(/[!'()*]/g, x => `%${x.charCodeAt(0).toString(16).toUpperCase()}`);


/***/ }),
```

which is your lib.

I've got this error:

```
ERROR in index.884a774e80700a169db9.js from UglifyJs
Unexpected token: operator (>) [index.884a774e80700a169db9.js:75386,22]
```

I know it's not directly the fault of this lib but do you have any idea why I've got this problem?

**Comment by kud** [comment]
Apparently it's because arrow func aren't supported and babel doesn't compile external libs, so `=>` doesn't work. I'll check that.

**Comment by kud** [comment]
Okay, that's it.

My babel config compiles my code from es6 or es7 to es5 but not external libs.

So for the moment, I've created a `lib/index.js` file and have:

```
const strictUriEncode = (str) => {
 return encodeURIComponent(str).replace(/[!'()*]/g, x => `%${x.charCodeAt(0).toString(16).toUpperCase()}`)
}

export { strictUriEncode }
```

:D

**Comment by kevva** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

**Comment by kud** [comment]
I understand your point of view but I wanted to use your lib as https://github.com/sindresorhus/query-string already uses it and it works like a charm in my browser.

I'll check babel-engine-plugin thanks.

By the way, it's a bit shame not to support browser no? as 

1/ it's exactly the same code
2/ it's quite the point of npm/browserify, etc

Anyway thank you for your time! :)

**Comment by kevva** [comment]
In this case, it's more an issue with Uglify not supporting anything but ES5 code than anything else. The code should work in the browser out of the box.

**Comment by kud** [comment]
You're perfectly right. Thank you. :)
